SKILL_KEYWORDS = {
    "ai": "AI",
    "alembic": "Alembic",
    "aws": "AWS",
    "azure": "Azure",
    "bootstrap": "Bootstrap",
    "c++": "C++",
    "css": "CSS",
    "docker": "Docker",
    "fastapi": "FastAPI",
    "flask": "Flask",
    "git": "Git",
    "github": "GitHub",
    "html": "HTML",
    "java": "Java",
    "javascript": "JavaScript",
    "jwt": "JWT",
    "kubernetes": "Kubernetes",
    "linux": "Linux",
    "machine learning": "Machine Learning",
    "mongodb": "MongoDB",
    "mysql": "MySQL",
    "nlp": "NLP",
    "node.js": "Node.js",
    "numpy": "NumPy",
    "pandas": "Pandas",
    "postgresql": "PostgreSQL",
    "power bi": "Power BI",
    "python": "Python",
    "react": "React",
    "rest api": "REST API",
    "scikit-learn": "scikit-learn",
    "sql": "SQL",
    "sqlalchemy": "SQLAlchemy",
    "tailwind": "Tailwind CSS",
    "tensorflow": "TensorFlow",
    "typescript": "TypeScript",
}
